import { useState } from 'react';
import { EmptyState } from '../../components/states.js';
import { JsonDetails, StatusBadge } from '../../components/ui.js';
import { Link } from '../../routes/router.js';
import { DataState, list, pickId, value } from '../shared.js';
import { ProjectFrame } from '../projects/ProjectFrame.js';
import { applySocialFilters, SocialCapabilityBadges, SocialFilterBar, SocialPageHeader, SocialReadOnlyNote, socialAuthor, socialCanonicalUrl, socialEngagement, socialSentiment, socialSourceLineage, socialStatus, socialTopics, useSocialQuery } from './social-shared.js';

export function SocialContentPage({ projectId }: { projectId?: string }) {
  const [filters, setFilters] = useState({ platform: '', status: '', query: '', sentiment: '', topic: '' });
  const query = useSocialQuery(projectId, 'content', filters);
  const items = applySocialFilters(list(query.data, 'items', 'content', 'posts'), filters);
  const page = <div className="tb-page tb-social-page"><SocialPageHeader eyebrow={projectId ? 'PROJECT SOCIAL / CONTENT' : 'SOCIAL / CONTENT'} title="内容" description={projectId ? '用筛选查看公开内容、作者、互动摘要和情绪标签；所有结果保留来源和项目上下文。' : '全局入口展示 /api/v2/social/overview 返回的内容样本；完整分页和项目筛选请进入具体项目。'} projectId={projectId} active="content" actions={<Link to={projectId ? `/projects/${encodeURIComponent(projectId)}/social/insights` : '/social/insights'} className="tb-button tb-button-primary">查看洞察 →</Link>}/><SocialFilterBar filters={filters} onChange={next => setFilters({ platform: next.platform ?? '', status: next.status ?? '', query: next.query ?? '', sentiment: next.sentiment ?? '', topic: next.topic ?? '' })} includeSentiment includeTopic/><section className="tb-card"><header className="tb-card-header"><div><p className="tb-eyebrow">{projectId ? 'PUBLIC CONTENT' : 'OVERVIEW SAMPLE'}</p><h2>内容信号</h2><p>这里是监听结果，不是社媒发布工作台；全局样本不伪造分页。</p></div><span className="tb-count-pill">{items.length} 条</span></header><DataState loading={query.loading} error={query.error} retry={query.retry} empty={<EmptyState title="暂无内容信号" description="v2 尚未返回公开内容或当前筛选下没有匹配结果。"/>}>{items.length === 0 ? <EmptyState title="暂无内容信号" description="调整平台、情绪、话题或关键词后重试。"/> : <div className="tb-social-content-grid">{items.slice(0, 60).map((item, index) => {const url = socialCanonicalUrl(item); const project = value(item, 'projectId', ''); return <article key={pickId(item) || index}><header><div className="tb-social-content-mark">▤</div><div><strong>{value(item, 'title', value(item, 'text', value(item, 'content', '未命名内容')))}</strong><small>{socialAuthor(item)} · {value(item, 'publishedAt', value(item, 'observedAt', value(item, 'capturedAt', '时间未提供')))}</small></div><StatusBadge value={socialSentiment(item, '') || socialStatus(item)}/></header><p>{value(item, 'summary', value(item, 'text', value(item, 'content', '内容摘要未提供。')))}</p><div className="tb-social-content-meta"><span>{value(item, 'platform', '平台未提供')}</span><span>互动 {socialEngagement(item)}</span><span>话题 {socialTopics(item)}</span><span>来源 {socialSourceLineage(item)}</span></div><SocialCapabilityBadges item={item}/><footer>{project && <Link to={`/projects/${encodeURIComponent(project)}/social`}>查看项目 →</Link>}{url.startsWith('http') && <a href={url} target="_blank" rel="noreferrer">打开来源 ↗</a>}</footer></article>})}</div>}</DataState><JsonDetails value={query.data} label="查看内容响应"/></section><SocialReadOnlyNote>内容页不提供任何外部写操作；社媒平台的发布、评论、点赞和 DM 均不在本产品 P0 范围内。</SocialReadOnlyNote></div>;
  return projectId ? <ProjectFrame projectId={projectId} section="social">{page}</ProjectFrame> : page;
}
