package com.threadbeacon.control.platform;

import com.threadbeacon.control.common.ApiException;
import com.threadbeacon.control.common.SecretBox;
import com.threadbeacon.control.common.CurrentUser;
import com.threadbeacon.control.common.Values;
import com.threadbeacon.control.job.JobService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

import java.net.URI;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;

import static com.threadbeacon.control.common.Values.*;

@Service
public class PlatformService {
    private static final List<Map<String,String>> TEMPLATES=List.of(Map.of("id","market-watch","name","市场舆情监测","description","跨平台采集、聚类、AI 归纳与自动交付"),Map.of("id","competitor","name","竞品研究","description","持续跟踪竞品、用户反馈与产品机会"),Map.of("id","content-radar","name","内容趋势雷达","description","发现高频主题并沉淀证据关系"),Map.of("id","blank","name","空白项目","description","从一个来源节点开始自由配置"));
    private final JdbcTemplate jdbc;private final TransactionTemplate transactions;private final ObjectMapper mapper;private final JobService jobs;private final SecretBox secrets;private final CurrentUser currentUser;private final ProductEventService productEvents;
    public PlatformService(JdbcTemplate jdbc,TransactionTemplate transactions,ObjectMapper mapper,JobService jobs,SecretBox secrets,CurrentUser currentUser,ProductEventService productEvents){this.jdbc=jdbc;this.transactions=transactions;this.mapper=mapper;this.jobs=jobs;this.secrets=secrets;this.currentUser=currentUser;this.productEvents=productEvents;}

    public Map<String,Object> studio(String ownerId){var workspace=workspace(ownerId);seedPlugins(ownerId);var result=new LinkedHashMap<String,Object>();result.put("workspace",workspace);result.put("templates",TEMPLATES);result.put("projects",jdbc.queryForList("SELECT * FROM projects WHERE owner_id=? ORDER BY updated_at DESC",ownerId));result.put("sources",jdbc.queryForList("SELECT s.*,c.cursor_json,c.last_success_at,c.last_job_id,c.consecutive_failures,c.last_error FROM project_sources s LEFT JOIN project_source_cursors c ON c.source_id=s.id WHERE s.owner_id=? ORDER BY s.created_at DESC",ownerId));result.put("plugins",jdbc.queryForList("SELECT * FROM plugin_installations WHERE owner_id=? ORDER BY status DESC,name",ownerId));result.put("profiles",jdbc.queryForList("SELECT * FROM browser_profiles WHERE owner_id=? ORDER BY created_at DESC",ownerId));result.put("skills",jdbc.queryForList("SELECT id,name,domain,capability,current_version,status FROM skills WHERE owner_id=? AND status='active' AND enabled=1 ORDER BY name",ownerId));result.put("relationships",jdbc.queryForList("SELECT rr.*,a.title AS source_title,b.title AS target_title FROM record_relationships rr JOIN records a ON a.id=rr.source_record_id JOIN records b ON b.id=rr.target_record_id WHERE rr.owner_id=? ORDER BY rr.created_at DESC LIMIT 100",ownerId));result.put("evidenceLinks",jdbc.queryForList("SELECT l.*,e.theme,r.title,r.author,r.platform,r.url FROM evidence_links l JOIN evidence e ON e.id=l.evidence_id JOIN records r ON r.id=l.record_id WHERE e.owner_id=? ORDER BY e.created_at DESC LIMIT 200",ownerId));result.put("checkpoints",jdbc.queryForList("SELECT c.*,r.workflow_id FROM workflow_checkpoints c JOIN workflow_runs r ON r.id=c.run_id WHERE r.owner_id=? ORDER BY COALESCE(c.finished_at,c.started_at) DESC LIMIT 200",ownerId));result.put("nodes",jdbc.queryForList("SELECT id,name,platform,version,capabilities_json,runtime_json,health_json,max_concurrency,status,active_jobs,last_seen_at FROM nodes ORDER BY last_seen_at DESC"));result.put("workflows",listWorkflows(ownerId,null));result.put("productMetrics",productEvents.metrics(ownerId,null));result.putAll(governance(ownerId));return result;}

    public Map<String,Object> createProject(String ownerId,Map<String,Object> body){var name=text(body.get("name"));if(name.isBlank()||name.length()>100)throw new ApiException(HttpStatus.BAD_REQUEST,"项目名称长度必须是 1-100");var workspace=workspace(ownerId);var projectId=id();var timestamp=now();var requestedTemplate=text(body.get("template"));var template=TEMPLATES.stream().anyMatch(item->item.get("id").equals(requestedTemplate))?requestedTemplate:"blank";var playbook="competitor".equals(template)?"competitive-research":"generic-research";jdbc.update("INSERT INTO projects(id,owner_id,workspace_id,name,description,template,playbook_key,playbook_version,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'active',?,?)",projectId,ownerId,workspace.get("id"),name,text(body.get("description")),template,playbook,"1.0",timestamp,timestamp);audit(ownerId,"project.create","project",projectId,Map.of("name",name,"template",template,"playbook",playbook));productEvents.track(ownerId,"project_created",projectId,"project",projectId,Map.of("template",template,"playbook",playbook));return jdbc.queryForMap("SELECT * FROM projects WHERE id=?",projectId);}

    public Map<String,Object> createSource(String ownerId,Map<String,Object> body){var projectId=text(body.get("projectId"));if(jdbc.queryForObject("SELECT count(*) FROM projects WHERE id=? AND owner_id=?",Integer.class,projectId,ownerId)!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"项目不存在");var name=text(body.get("name"));var kind=text(body.get("kind"));if(name.isBlank()||!Set.of("native","opencli","rss","rest","web").contains(kind))throw new ApiException(HttpStatus.BAD_REQUEST,"数据源名称或类型无效");var config=new LinkedHashMap<>(object(body.get("config")));var endpoint=text(config.remove("endpoint"));if(endpoint.isBlank())endpoint=text(config.get("url"));if(Set.of("rss","rest","web").contains(kind)){validatePublicUrl(endpoint);config.put("url",endpoint);}else if(!endpoint.isBlank())config.put("platform",kind.equals("opencli")&&!endpoint.startsWith("opencli:")?"opencli:"+endpoint:endpoint);var sourceId=id();var timestamp=now();jdbc.update("INSERT INTO project_sources(id,project_id,owner_id,name,kind,config_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'configured',?,?)",sourceId,projectId,ownerId,name,kind,json(mapper,config),timestamp,timestamp);audit(ownerId,"source.create","project_source",sourceId,Map.of("projectId",projectId,"kind",kind));return jdbc.queryForMap("SELECT * FROM project_sources WHERE id=?",sourceId);}

    public Map<String,Object> testSource(String ownerId,String sourceId){var rows=jdbc.queryForList("SELECT s.*,c.cursor_json FROM project_sources s LEFT JOIN project_source_cursors c ON c.source_id=s.id WHERE s.id=? AND s.owner_id=?",sourceId,ownerId);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"项目数据源不存在");var source=rows.get(0);var config=new LinkedHashMap<>(parseMap(text(source.get("config_json"))));var kind=text(source.get("kind"));if(Set.of("rss","rest","web").contains(kind)){var cursor=parseMap(text(source.get("cursor_json")));if(!cursor.isEmpty())config.put("cursor",cursor);}var platform=Set.of("rss","rest","web").contains(kind)?kind:text(config.get("platform"));if(kind.equals("opencli")&&!platform.startsWith("opencli:"))platform="opencli:"+platform;var input=Map.<String,Object>of("platform",platform,"keyword",text(config.get("keyword")).isBlank()?text(source.get("name")):text(config.get("keyword")),"limit",20,"includeComments",false,"priority",10);var job=jobs.insert(ownerId,input,Map.of("projectId",source.get("project_id"),"sourceId",sourceId,"sourceTest",true,"config",config));var timestamp=now();jdbc.update("UPDATE project_sources SET status='testing',updated_at=? WHERE id=?",timestamp,sourceId);jdbc.update("INSERT INTO project_source_cursors(source_id,owner_id,cursor_json,last_job_id,consecutive_failures,updated_at) VALUES(?,?,'{}',?,0,?) ON CONFLICT(source_id) DO UPDATE SET last_job_id=excluded.last_job_id,updated_at=excluded.updated_at",sourceId,ownerId,job.get("id"),timestamp);return job;}

    public Map<String,Object> createProfile(String ownerId,Map<String,Object> body){var name=text(body.get("name"));var profileName=text(body.get("profileName"));if(name.isBlank()||profileName.isBlank()||name.length()>80||profileName.length()>100)throw new ApiException(HttpStatus.BAD_REQUEST,"浏览器配置名称无效");var profileId=id();var timestamp=now();var kind="anonymous".equals(body.get("profileKind"))?"anonymous":"authenticated";var mode=Set.of("cdp","bridge","local").contains(text(body.get("mode")))?text(body.get("mode")):"cdp";jdbc.update("INSERT INTO browser_profiles(id,owner_id,name,profile_name,mode,status,profile_kind,node_id,site_bindings_json,no_vnc_url,cdp_url,attestation_json,created_at,updated_at) VALUES(?,?,?,?,?,'configured',?,?,?,?,?,'{}',?,?)",profileId,ownerId,name,profileName,mode,kind,emptyToNull(text(body.get("nodeId"))),json(mapper,strings(body.get("sites"))),safeEndpoint(body.get("noVncUrl")),safeEndpoint(body.get("cdpUrl")),timestamp,timestamp);audit(ownerId,"browser_profile.create","browser_profile",profileId,Map.of("profileKind",kind,"mode",mode));return jdbc.queryForMap("SELECT * FROM browser_profiles WHERE id=?",profileId);}

    public List<Map<String,Object>> listWorkflows(String ownerId,String projectId){return projectId==null?jdbc.queryForList("SELECT * FROM workflows WHERE owner_id=? ORDER BY updated_at DESC",ownerId):jdbc.queryForList("SELECT * FROM workflows WHERE owner_id=? AND project_id=? ORDER BY updated_at DESC",ownerId,projectId);}
    public Map<String,Object> productMetrics(String ownerId,String projectId){var filter=projectId==null?"":projectId.trim();if(!filter.isBlank()&&jdbc.queryForObject("SELECT count(*) FROM projects WHERE id=? AND owner_id=?",Integer.class,filter,ownerId)!=1)throw new ApiException(HttpStatus.NOT_FOUND,"项目不存在");return productEvents.metrics(ownerId,filter);}
    public Map<String,Object> createWorkflow(String ownerId,Map<String,Object> body){var name=text(body.get("name"));if(name.isBlank()||name.length()>80)throw new ApiException(HttpStatus.BAD_REQUEST,"工作流名称长度必须是 1-80");var projectId=emptyToNull(text(body.get("projectId")));if(projectId!=null&&jdbc.queryForObject("SELECT count(*) FROM projects WHERE id=? AND owner_id=?",Integer.class,projectId,ownerId)!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"项目不存在");var spec=normalizeSpec(object(body.get("spec")));validateSkillBindings(ownerId,spec);var workflowId=id();var timestamp=now();jdbc.update("INSERT INTO workflows(id,owner_id,project_id,name,description,draft_json,revision,published_version,created_at,updated_at) VALUES(?,?,?,?,?,?,1,0,?,?)",workflowId,ownerId,projectId,name,text(body.get("description")),json(mapper,spec),timestamp,timestamp);audit(ownerId,"workflow.create","workflow",workflowId,Map.of("name",name));return jdbc.queryForMap("SELECT * FROM workflows WHERE id=?",workflowId);}
    public Map<String,Object> workflow(String ownerId,String workflowId){var rows=jdbc.queryForList("SELECT * FROM workflows WHERE id=? AND owner_id=?",workflowId,ownerId);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"工作流不存在");return rows.get(0);}
    public Map<String,Object> saveWorkflow(String ownerId,String workflowId,Map<String,Object> body){var current=workflow(ownerId,workflowId);var revision=integer(body.get("revision"),0);if(integer(current.get("revision"),1)!=revision)throw new ApiException(HttpStatus.CONFLICT,"草稿版本冲突，请刷新");var spec=normalizeSpec(object(body.get("spec")));validateSkillBindings(ownerId,spec);var changed=jdbc.update("UPDATE workflows SET draft_json=?,revision=revision+1,updated_at=? WHERE id=? AND owner_id=? AND revision=?",json(mapper,spec),now(),workflowId,ownerId,revision);if(changed!=1)throw new ApiException(HttpStatus.CONFLICT,"草稿版本冲突，请刷新");return workflow(ownerId,workflowId);}
    public Map<String,Object> publish(String ownerId,String workflowId){var current=workflow(ownerId,workflowId);var spec=parseMap(text(current.get("draft_json")));WorkflowSpecPolicy.validate(spec);WorkflowSpecPolicy.validateExecutable(spec);validateSkillBindings(ownerId,spec);var version=integer(current.get("published_version"),0)+1;var versionId=id();var timestamp=now();transactions.executeWithoutResult(status->{jdbc.update("INSERT INTO workflow_versions(id,workflow_id,owner_id,version,spec_json,created_at) VALUES(?,?,?,?,?,?)",versionId,workflowId,ownerId,version,current.get("draft_json"),timestamp);jdbc.update("UPDATE workflows SET published_version=?,updated_at=? WHERE id=?",version,timestamp,workflowId);});return jdbc.queryForMap("SELECT * FROM workflow_versions WHERE id=?",versionId);}

    public Map<String,Object> run(String ownerId,String workflowId){var versions=jdbc.queryForList("SELECT v.*,w.project_id FROM workflow_versions v JOIN workflows w ON w.id=v.workflow_id WHERE v.workflow_id=? AND v.owner_id=? ORDER BY v.version DESC LIMIT 1",workflowId,ownerId);if(versions.isEmpty())throw new ApiException(HttpStatus.CONFLICT,"请先发布工作流");var version=versions.get(0);var spec=parseMap(text(version.get("spec_json")));var sourceNodes=array(spec.get("nodes")).stream().map(Values::object).filter(node->"source".equals(text(node.get("type")))).toList();if(sourceNodes.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"工作流缺少来源节点");var created=new ArrayList<Map<String,Object>>();for(var node:sourceNodes){var source=object(node.get("config"));var options=new LinkedHashMap<String,Object>();options.put("projectId",version.get("project_id"));options.put("workflowSpec",spec);options.put("workflowSourceNodeId",node.get("id"));var input=new LinkedHashMap<String,Object>();input.put("platform",source.get("platform"));input.put("keyword",source.get("keyword"));input.put("limit",source.getOrDefault("limit",100));input.put("includeComments",source.getOrDefault("includeComments",true));created.add(jobs.insert(ownerId,input,options));}var runId=id();var timestamp=now();transactions.executeWithoutResult(status->{jdbc.update("INSERT INTO workflow_runs(id,workflow_id,version_id,owner_id,job_id,status,started_at,trigger_json,updated_at) VALUES(?,?,?,?,?,'queued',?,'{}',?)",runId,workflowId,version.get("id"),ownerId,created.get(0).get("id"),timestamp,timestamp);for(int index=0;index<created.size();index++){var node=sourceNodes.get(index);var jobId=created.get(index).get("id");jdbc.update("UPDATE jobs SET workflow_run_id=? WHERE id=? AND owner_id=?",runId,jobId,ownerId);jdbc.update("INSERT INTO workflow_run_jobs(id,run_id,job_id,source_node_id,status,result_json,created_at,updated_at) VALUES(?,?,?,?,'queued',NULL,?,?)",id(),runId,jobId,node.get("id"),timestamp,timestamp);}for(var node:array(spec.get("nodes"))){var value=object(node);jdbc.update("INSERT INTO workflow_checkpoints(id,run_id,node_id,status,input_json,updated_at) VALUES(?,?,?,'pending',?,?)",id(),runId,value.get("id"),"source".equals(value.get("type"))?json(mapper,value.get("config")):"{}",timestamp);}jdbc.update("INSERT INTO workflow_events(id,run_id,node_id,type,message,payload_json,created_at) VALUES(?,?,?,'queued',?,? ,?)",id(),runId,"runtime",created.size()+" 个来源任务已进入执行队列",json(mapper,Map.of("jobIds",created.stream().map(job->job.get("id")).toList())),timestamp);});return Map.of("workflowRunId",runId,"jobIds",created.stream().map(job->job.get("id")).toList());}

    public Map<String,Object> runDetails(String ownerId,String runId){var runs=jdbc.queryForList("SELECT r.*,w.name AS workflow_name,p.name AS project_name,v.version,v.spec_json FROM workflow_runs r JOIN workflows w ON w.id=r.workflow_id LEFT JOIN projects p ON p.id=w.project_id JOIN workflow_versions v ON v.id=r.version_id WHERE r.id=? AND r.owner_id=?",runId,ownerId);if(runs.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"运行记录不存在");return Map.of("run",runs.get(0),"jobs",jdbc.queryForList("SELECT j.source_node_id,j.status AS workflow_status,j.result_json,q.* FROM workflow_run_jobs j JOIN jobs q ON q.id=j.job_id WHERE j.run_id=? ORDER BY j.created_at",runId),"events",jdbc.queryForList("SELECT * FROM workflow_events WHERE run_id=? ORDER BY created_at",runId),"checkpoints",jdbc.queryForList("SELECT * FROM workflow_checkpoints WHERE run_id=? ORDER BY COALESCE(started_at,finished_at)",runId));}

    public Map<String,Object> governance(String ownerId){var result=new LinkedHashMap<String,Object>();result.put("evidence",jdbc.queryForList("SELECT e.*,COALESCE((SELECT count(*) FROM evidence_links l WHERE l.evidence_id=e.id),0) AS linked_count FROM evidence e WHERE e.owner_id=? ORDER BY e.created_at DESC LIMIT 100",ownerId));result.put("auditLogs",jdbc.queryForList("SELECT * FROM audit_logs WHERE owner_id=? ORDER BY created_at DESC LIMIT 200",ownerId));result.put("rules",jdbc.queryForList("SELECT id,owner_id,project_id,name,kind,enabled,created_at,updated_at FROM delivery_rules WHERE owner_id=? ORDER BY created_at DESC",ownerId));result.put("deliveryLogs",jdbc.queryForList("SELECT * FROM delivery_logs WHERE owner_id=? ORDER BY created_at DESC LIMIT 50",ownerId));result.put("runs",jdbc.queryForList("SELECT r.*,w.name AS workflow_name,p.name AS project_name,v.version FROM workflow_runs r JOIN workflows w ON w.id=r.workflow_id LEFT JOIN projects p ON p.id=w.project_id JOIN workflow_versions v ON v.id=r.version_id WHERE r.owner_id=? ORDER BY r.started_at DESC LIMIT 100",ownerId));result.put("events",jdbc.queryForList("SELECT e.* FROM workflow_events e JOIN workflow_runs r ON r.id=e.run_id WHERE r.owner_id=? ORDER BY e.created_at DESC LIMIT 200",ownerId));result.put("workspace",workspace(ownerId));return result;}
    public Map<String,Object> createRule(String ownerId,Map<String,Object> body){var name=text(body.get("name"));var kind=text(body.get("kind"));var endpoint=text(body.get("endpoint"));var projectId=emptyToNull(text(body.get("projectId")));if(name.isBlank()||!Set.of("webhook","feishu","dingtalk","wecom","email").contains(kind))throw new ApiException(HttpStatus.BAD_REQUEST,"交付规则无效");if(projectId!=null&&jdbc.queryForObject("SELECT count(*) FROM projects WHERE id=? AND owner_id=?",Integer.class,projectId,ownerId)!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"项目不存在");validatePublicUrl(endpoint);var ruleId=id();var timestamp=now();jdbc.update("INSERT INTO delivery_rules(id,owner_id,project_id,name,kind,endpoint_encrypted,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)",ruleId,ownerId,projectId,name,kind,secrets.encrypt(endpoint),timestamp,timestamp);audit(ownerId,"delivery_rule.create","delivery_rule",ruleId,Map.of("kind",kind,"projectId",projectId==null?"global":projectId));return jdbc.queryForMap("SELECT id,owner_id,project_id,name,kind,enabled,created_at,updated_at FROM delivery_rules WHERE id=?",ruleId);}
    public void toggleRule(String ownerId,String ruleId){if(jdbc.update("UPDATE delivery_rules SET enabled=CASE enabled WHEN 1 THEN 0 ELSE 1 END,updated_at=? WHERE id=? AND owner_id=?",now(),ruleId,ownerId)!=1)throw new ApiException(HttpStatus.NOT_FOUND,"交付规则不存在");}

    private Map<String,Object> workspace(String ownerId){var rows=jdbc.queryForList("SELECT * FROM workspaces WHERE owner_id=?",ownerId);var created=rows.isEmpty();if(created){var workspaceId=id();var timestamp=now();jdbc.update("INSERT INTO workspaces(id,owner_id,name,created_at,updated_at) VALUES(?,?,'个人工作区',?,?) ON CONFLICT(owner_id) DO NOTHING",workspaceId,ownerId,timestamp,timestamp);workspaceId=text(jdbc.queryForMap("SELECT id FROM workspaces WHERE owner_id=?",ownerId).get("id"));jdbc.update("INSERT INTO workspace_members(id,workspace_id,user_id,role,created_at) VALUES(?,?,?,'owner',?) ON CONFLICT(workspace_id,user_id) DO NOTHING",id(),workspaceId,ownerId,timestamp);rows=jdbc.queryForList("SELECT * FROM workspaces WHERE owner_id=?",ownerId);productEvents.track(ownerId,"workspace_ready",null,"workspace",workspaceId,Map.of("created",true));}var result=new LinkedHashMap<String,Object>(rows.get(0));var membership=jdbc.queryForList("SELECT role FROM workspace_members WHERE workspace_id=? AND user_id=?",result.get("id"),currentUser.userId());result.put("role",membership.isEmpty()?"viewer":membership.get(0).get("role"));return result;}
    private void seedPlugins(String ownerId){var timestamp=now();for(var plugin:List.of(new String[]{"native-social","原生社媒连接器","source"},new String[]{"opencli","OpenCLI 动态适配","source"},new String[]{"browser-cdp","浏览器 CDP 运行时","runtime"},new String[]{"agent-skill","Agent Skill 治理与纠错","runtime"},new String[]{"analysis","聚类与 LLM 分析","processor"},new String[]{"delivery","多渠道交付","delivery"},new String[]{"mcp-server","MCP 消费接口","integration"})){jdbc.update("INSERT INTO plugin_installations(id,owner_id,plugin_key,name,kind,version,status,capabilities_json,created_at,updated_at) VALUES(?,?,?,?,?,'1.0.0','installed','[]',?,?) ON CONFLICT(owner_id,plugin_key) DO UPDATE SET updated_at=excluded.updated_at",id(),ownerId,plugin[0],plugin[1],plugin[2],timestamp,timestamp);}}
    private Map<String,Object> normalizeSpec(Map<String,Object> input){
        var spec=new LinkedHashMap<>(input);var nodes=array(spec.get("nodes"));
        if(nodes.isEmpty()){
            var sources=array(spec.get("sources"));
            if(sources.isEmpty()&&!object(spec.get("source")).isEmpty())sources=List.of(spec.get("source"));
            var built=new ArrayList<Map<String,Object>>();var sourceIds=new ArrayList<String>();int index=0;
            for(var source:sources){index++;var sourceId="source-"+index;sourceIds.add(sourceId);built.add(Map.of("id",sourceId,"type","source","label","采集来源 "+index,"x",0,"y",0,"config",object(source)));}
            var stepIds=new ArrayList<String>();index=0;
            for(var step:strings(spec.get("steps"))){index++;var stepId=step+"-"+index;stepIds.add(stepId);built.add(Map.of("id",stepId,"type",step,"label",step,"x",0,"y",0,"config",Map.of()));}
            var edges=new ArrayList<Map<String,Object>>();
            if(!stepIds.isEmpty())for(var sourceId:sourceIds)edges.add(Map.of("id","edge-"+sourceId+"-"+stepIds.get(0),"source",sourceId,"target",stepIds.get(0)));
            for(int next=1;next<stepIds.size();next++)edges.add(Map.of("id","edge-step-"+next,"source",stepIds.get(next-1),"target",stepIds.get(next)));
            spec.put("nodes",built);spec.put("edges",edges);
        }
        WorkflowSpecPolicy.validate(spec);return spec;
    }
    private void validateSkillBindings(String ownerId,Map<String,Object> spec){for(var skillId:WorkflowSpecPolicy.agentSkillIds(spec)){if(jdbc.queryForObject("SELECT count(*) FROM skills WHERE id=? AND owner_id=? AND status='active' AND enabled=1",Integer.class,skillId,ownerId)!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"Agent 节点绑定的 Skill 不存在或未发布："+skillId);}}
    private Map<String,Object> parseMap(String value){try{return mapper.readValue(value,new TypeReference<Map<String,Object>>(){});}catch(Exception ignored){return Map.of();}}
    private void audit(String owner,String action,String resourceType,String resourceId,Object detail){jdbc.update("INSERT INTO audit_logs(id,owner_id,action,resource_type,resource_id,detail_json,created_at) VALUES(?,?,?,?,?,?,?)",id(),owner,action,resourceType,resourceId,json(mapper,detail),now());}
    private void validatePublicUrl(String value){try{parsePublicUrl(value);}catch(Exception error){throw new ApiException(HttpStatus.BAD_REQUEST,"URL 必须是公网 HTTP/HTTPS 地址");}}
    static URI parsePublicUrl(String value){var expanded=value.replace("{keyword}","threadbeacon").replace("{limit}","1");if(expanded.contains("{")||expanded.contains("}"))throw new IllegalArgumentException();var uri=URI.create(expanded);if(!Set.of("http","https").contains(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null)throw new IllegalArgumentException();var host=uri.getHost().toLowerCase();if(host.equals("localhost")||host.endsWith(".local")||host.matches("^(127\\.|10\\.|192\\.168\\.|169\\.254\\.).*"))throw new IllegalArgumentException();return uri;}
    private String safeEndpoint(Object value){var text=text(value);if(text.isBlank())return null;try{var uri=URI.create(text);if(uri.getUserInfo()!=null||!Set.of("http","https","ws","wss").contains(uri.getScheme()))throw new IllegalArgumentException();return uri.toString();}catch(Exception error){throw new ApiException(HttpStatus.BAD_REQUEST,"浏览器端点无效");}}
    private String emptyToNull(String value){return value.isBlank()?null:value;}
}
