const flow=[
  ['01','定义研究项目','明确主题、来源、频率、合规边界与交付目标。'],
  ['02','接入可信来源','优先使用开放协议与官方 API；登录态只用于自有账号。'],
  ['03','标准化与去重','统一作者、链接、时间、互动量和原始字段，保存增量游标。'],
  ['04','编排分析节点','过滤、闸门、聚类、LLM 与受治理 Agent 按 DAG 执行。'],
  ['05','建立证据关系','模型发现连接到原始记录、检查点、版本和运行 Trace。'],
  ['06','报告与自动交付','报告写入对象存储，并经 Webhook 或企业渠道交付。'],
];
const nodes=[['Source','采集来源','按平台能力与 Worker 路由任务'],['Normalize','标准化','收敛为统一 SourceItem'],['Dedupe / Filter','清洗','跨任务去重并过滤低价值内容'],['Gate','人工或规则闸门','风险动作确认与质量门槛'],['Cluster','聚类','把大量表达归并为问题主题'],['LLM / Agent','研究推理','有界总结或受治理的多步执行'],['Report / Dataset','资产化','生成证据报告和可查询数据集'],['Deliver','交付','Webhook 与企业消息渠道自动触达']];

export function ProductGuide(){return <main className="about-shell">
  <header className="about-nav"><a href="/" className="about-brand"><span>TB</span><strong>ThreadBeacon</strong></a><nav><a href="#problem">解决的问题</a><a href="#architecture">后端架构</a><a href="#flow">核心流程</a><a className="about-enter" href="/">进入控制台</a></nav></header>
  <section className="about-hero"><div><p className="eyebrow">PROJECT BACKGROUND</p><h1>面向研究团队的<br/><em>开源情报工作流平台</em></h1><p>公开信息分散在社交平台、网站、API 和浏览器会话中。ThreadBeacon 把采集、治理、分析、证据和交付放进同一条可审计流水线，让研究结果不只是模型生成的一段文字。</p><div><a href="#architecture">查看系统架构</a><a href="https://github.com/chuanxu742-glitch/threadbeacon" target="_blank" rel="noreferrer">查看源代码 ↗</a></div></div><aside><span>CONTROL PLANE</span><strong>可信研究需要的不只是 AI</strong><ul><li>来源与授权边界</li><li>可恢复的执行状态</li><li>原始记录与证据关系</li><li>模型与 Skill 的治理</li></ul></aside></section>
  <section className="about-section problem-section" id="problem"><div className="section-intro"><p className="eyebrow">WHY THREADBEACON</p><h2>它解决的不是“抓到数据”，<br/>而是“持续产出可信研究”。</h2></div><div className="problem-grid"><article><b>01</b><h3>信息来源碎片化</h3><p>不同平台字段、凭据和增量机制各不相同，传统脚本难以长期维护。</p><span>统一 Provider 契约与来源游标</span></article><article><b>02</b><h3>AI 结论无法回溯</h3><p>只有摘要、没有原文关系和运行上下文，很难复核、分享或用于决策。</p><span>证据链接、版本与 Trace</span></article><article><b>03</b><h3>流程无法复用</h3><p>一次性提示词和手工整理不能稳定重跑，也不能安全交给团队协作。</p><span>DAG、计划任务与治理 Skill</span></article><article><b>04</b><h3>合规边界模糊</h3><p>登录态、平台 API 和公开网页混在一起，容易扩大凭据与访问风险。</p><span>能力路由、最小权限与审计</span></article></div></section>
  <section className="about-section architecture-section" id="architecture"><div className="section-intro"><p className="eyebrow">BACKEND ARCHITECTURE</p><h2>控制面管治理，Worker 管执行，<br/>数据与凭据各守边界。</h2><p>Spring Boot 负责身份、租约、工作流和审计；TypeScript Worker 只上报自身具备的能力并执行任务。平台密钥和浏览器登录态留在执行节点。</p></div><div className="architecture-map"><div className="arch-users"><span>研究人员</span><span>MCP / API Client</span><span>企业 OIDC</span></div><i>HTTPS / PAT</i><div className="arch-control"><header><b>Java Control Plane</b><small>Spring Boot · Security · Flyway</small></header><div><span>身份与工作区</span><span>任务 / 租约</span><span>工作流 DAG</span><span>Skill 治理</span><span>审计与交付</span></div></div><div className="arch-stores"><article><b>PostgreSQL</b><small>状态 · 记录 · 证据 · 审计</small></article><article><b>S3 / MinIO</b><small>报告 · 截图 · Trace</small></article></div><i>Polling / HTTPS / WSS Gateway</i><div className="arch-workers"><article><b>Worker Fleet</b><small>能力发现 · 抢单 · 重试 · 回传</small></article><article><b>Browser Profile</b><small>CDP · 自有登录态 · 域名白名单</small></article><article><b>Providers</b><small>开放协议 · 官方 API · 授权来源</small></article></div></div><div className="architecture-notes"><article><strong>控制平面不保存平台 API Key</strong><p>任务只派给声明相应能力的在线 Worker。</p></article><article><strong>Gateway 当前保持单副本</strong><p>Agent 可自动重连；多 Gateway 需要外部协调存储。</p></article><article><strong>任意代码默认不执行</strong><p>Dify code/tool/plugin 在强隔离沙箱完成前保持阻断。</p></article></div></section>
  <section className="about-section flow-section" id="flow"><div className="section-intro"><p className="eyebrow">CORE WORKFLOW</p><h2>从问题到证据资产的六个阶段</h2></div><div className="flow-timeline">{flow.map(([number,title,copy])=><article key={number}><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><div className="node-catalog"><header><h3>核心流程节点</h3><p>节点通过有向无环图连接，支持多来源分支、汇聚、检查点和失败恢复。</p></header><div>{nodes.map(([name,label,copy])=><article key={name}><code>{name}</code><strong>{label}</strong><p>{copy}</p></article>)}</div></div></section>
  <section className="about-cta"><p className="eyebrow">OPEN SOURCE · SELF-HOSTED</p><h2>把一次调查，沉淀成可重复运行的研究系统。</h2><div><a href="/">进入控制台</a><a href="/docs">查看 API</a></div></section>
  <footer className="about-footer"><span>ThreadBeacon · Apache-2.0</span><span>公开数据研究不等于平台授权，使用者需遵守适用法律与服务条款。</span></footer>
  </main>}
